#!/usr/bin/env python3
"""Generate _data/github_repo_metadata.yml from _data/repositories.yml."""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
REPOSITORIES_FILE = ROOT / "_data" / "repositories.yml"
OUTPUT_FILE = ROOT / "_data" / "github_repo_metadata.yml"
GITHUB_API = "https://api.github.com/repos/"


def load_repo_names(path: Path) -> list[str]:
    repos: list[str] = []
    in_repos = False

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        if stripped == "repos:":
            in_repos = True
            continue

        if in_repos and stripped.startswith("- "):
            entry = stripped[2:].strip()
            if entry.startswith("name:"):
                repo = entry.removeprefix("name:").strip().strip('"').strip("'")
            else:
                repo = entry.strip('"').strip("'")
            if "/" in repo:
                repos.append(repo)
            continue

        if in_repos and stripped and not raw_line.startswith(" "):
            in_repos = False

    return list(dict.fromkeys(repos))


def fetch_repo_metadata(full_name: str) -> dict[str, Any]:
    token = os.environ.get("GITHUB_TOKEN")
    request = urllib.request.Request(
        GITHUB_API + full_name,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "repo-metadata-updater",
            **({"Authorization": f"Bearer {token}"} if token else {}),
        },
    )

    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            data = json.load(response)
    except urllib.error.HTTPError as error:
        body = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API error for {full_name}: {error.code} {body}") from error

    license_info = data.get("license") or {}
    owner_info = data.get("owner") or {}

    return {
        "name": data.get("name"),
        "owner": owner_info.get("login"),
        "full_name": data.get("full_name"),
        "url": data.get("html_url"),
        "description": data.get("description"),
        "homepage": data.get("homepage"),
        "language": data.get("language"),
        "stars": data.get("stargazers_count"),
        "forks": data.get("forks_count"),
        "watchers": data.get("watchers_count"),
        "open_issues": data.get("open_issues_count"),
        "license": license_info.get("spdx_id"),
        "topics": data.get("topics") or [],
        "archived": data.get("archived"),
        "fork": data.get("fork"),
        "pushed_at": data.get("pushed_at"),
        "updated_at": data.get("updated_at"),
        "created_at": data.get("created_at"),
        "default_branch": data.get("default_branch"),
        "visibility": data.get("visibility"),
        "size": data.get("size"),
    }


def yaml_scalar(value: Any) -> str:
    if value is None:
        return '""'
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)


def dump_metadata(metadata: dict[str, dict[str, Any]]) -> str:
    lines = [
        "# This file is generated by _scripts/update_repo_metadata.py.",
        "# Edit _data/repositories.yml to change the displayed repositories.",
    ]

    for full_name, values in metadata.items():
        lines.append(f"{json.dumps(full_name, ensure_ascii=False)}:")
        for key, value in values.items():
            if isinstance(value, list):
                if value:
                    lines.append(f"  {key}:")
                    for item in value:
                        lines.append(f"    - {yaml_scalar(item)}")
                else:
                    lines.append(f"  {key}: []")
            else:
                lines.append(f"  {key}: {yaml_scalar(value)}")

    return "\n".join(lines) + "\n"


def main() -> int:
    repo_names = load_repo_names(REPOSITORIES_FILE)
    if not repo_names:
        print(f"No repositories found in {REPOSITORIES_FILE}", file=sys.stderr)
        return 1

    metadata = {repo: fetch_repo_metadata(repo) for repo in repo_names}
    OUTPUT_FILE.write_text(dump_metadata(metadata), encoding="utf-8")
    print(f"Wrote metadata for {len(metadata)} repositories to {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
